# https://github.com/AdguardTeam/dnsproxy/raw/master/config.yaml.dist
# https://github.com/AdguardTeam/dnsproxy/tree/master

# This is the yaml configuration file for dnsproxy with minimal working
# configuration, all the options available can be seen with ./dnsproxy --help.
# To use it within dnsproxy specify the --config-path=/<path-to-config.yaml>
# option.  Any other command-line options specified will override the values
# from the config file.
---
timeout: "10s"
bootstrap:
  - "1.1.1.1:53"
listen-addrs:
  - "::"
http3: true
upstream:
